# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# ATTEMPT 1
# sum = 0 
# x = 1
# y = 2

# while y < 4000000
#     x,y = y, x + y
#     if y.even? == true
#         sum += y
#     end 
# end

# sum

# ATTEMPT 2
sum = 0
a = [1,2]

while a[-1] + a[-2] < 4000000
    a << a[-1] + a[-2]
end

a.each do |num|
    sum += num if num.even?
end 

print sum